theme: jekyll-theme-minimal
title: SMTPLW - SMTP Locaweb API client
description: The Locaweb dedicated SMTP service API client.
logo: https://raw.githubusercontent.com/guibranco/smtplw/main/logo.jpg
show_downloads: true